# fly.toml app configuration file generated for ai-study-buddy on 2025-05-10T22:39:09+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-study-buddy'
primary_region = 'otp'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
